amylour/star_wars_hackathon

- README.md
> PR test - pew pew

- index.html
- Created HTML file
- Created assets folder with CSS + JS folders
- Created and imported CSS + JS files into HTML document
- Additionally I have added the Bootstrap CDN into the HTML document
> Setup: Create basic project set-up

- index.html
Changed CSS + JS file paths to relative file paths
> Fix assets file path

- assets/css/style.css
- index.html
- Creation of basic bootstrap navbar
- Creation of game container in html file + css
> Feat: Add navbar + game container

- assets/css/style.css
- index.html
We need to discuss potential font and colouring of the text, but this is in a good place at the moment
> Add Basic styling and positioning to the footer

- assets/css/style.css
- assets/js/script.js
- index.html
- Created Start Modal
- Added JS for onload and disappear onclick
- Added basic styling
> Add start modal and styling

- assets/css/style.css
- index.html
Work still needs to be done on the Javascript side to dismiss this message but it's base is in place
> Add non-desktop message + reposition start button

- assets/js/script.js
- Wrote some basic outline functions for scores and game-over. Nothing major but it's a starting point for tomorrow.
> Feat: Write some basic JS outline functions

- assets/css/style.css
- assets/js/script.js
- index.html
- Created the frontend modal in HTML and CSS files
- Functionality in JS is there but will need tweaking - such as the restart function needing to reset the correct variables. Right now i;ve left it commented. 
- The modal itself will need decorating too and its pure basic.
- You may notice a lot of extra small changes - this is because i have a habit of having Prettier clean all the codebase. shouldn't affect the program however.
> Feat: Create modal in HTML+CSS + add functionality in JS file

- assets/js/script.js
Lightsabre goes to 0, 0 upon collision.
> Tie fighter and lightsaber collision now works

- assets/css/style.css
- assets/js/script.js
- index.html
- Create life containers on the frontend
- I used a Storm trooper helmet HOWEVER, it would be amazing if @amylour you could add a Grogu head instead! might be cute.
- The JS functionality is there but needs wiring up eventually. not yet functional.
> Feat: Create life containers on frontend + add basic JS logic

- assets/js/script.js
Bug from merging shaun's branch. Accidental. Fixed.
> Fix/bug: Restore missing code from merge conflict

- README.md
Add existing features to the readme file
> Add existing features to readme file

- assets/js/script.js
A few minor changes to collision detection
> tightened up collision detection a bit more

- assets/js/script.js
All sprites now react when they collide with one another
> all moving sprites now have collision detection

- assets/js/script.js
>  BF helmet commented out for use in 2nd level vader speed increases upon collision

- assets/css/style.css
- assets/js/script.js
- index.html
- Created points board in HTML file + CSS
- Readjusted spacing of life containers, timer and points board so that they are more neat (subjectively speaking of course)
- Created function to add points when touching one of the sprites - I think to the Clone.
- Still need some minor work so that it is reflective of what we want.
- Needs to have a function where it reaches a max 100 points (for example), and then calls another function perhaps called winGame()
> Keiron: Points system

- assets/js/script.js
- index.html
> Add beginings of sound toggle

- assets/js/script.js
>  Tie Fighter collision much more accurate, sprite speeds increased slightly

- assets/js/script.js
- Create the basis of the gameOver() function 
- Need stills major work, but wanted to get it into the code-base
> Keiron: Basic gameOver() function 

- assets/js/script.js
Need to check how to fix the scaling speed. It works for the first game over but fails after a few. Also maybe look into resetting sprite positions as you sometimes instant game over if you die to vader near the lightsaber spawn
> Partial fix for new game movement. Needs more work

- assets/js/script.js
- index.html
- Created the gameWon() function and modal
- For some reason, I can't use the restartGame() function, which I am using on the gameOver() function. Not really understanding why. Will explore as from tomorrow morning.
> Feat: Create gameWon() function + modal

- assets/js/script.js
- Fixed bug to control life containers
> Fix: Stop life containers overflowing past 3 containers

- assets/js/script.js
- index.html
- Modified the gameWon modal to include an anchor tag with a href to the next file
- FILE PATH IS RELATIVE xD xD 
- Lowered the win capacity to 50 points rather than 100 points
> Add path to level 2 file

- assets/css/style.css
- Created game-canvas-2 and game-canvas 3 for 2nd and 3rd level backgrounds
> Add game canvas 2/3 for levels

- assets/css/style.css
- level2.html
Bug: Misunderstanding in CSS ids and JS wiring. Amy clarified and sort the issue in this PR.
> Amy: Fix game canvas 2 for gameplay

- level2.html
- level3.html
- Modals for Start Level 3, gameWon and gameOver now have suitable contexts. We could ideally change them some more however.
> Change modals and level passing to suit new mounted levels

- assets/css/style.css
- assets/js/level2.js
- assets/js/level3.js
- assets/js/script.js
- index.html
- level2.html
- level3.html
- Ran Prettier throughout files in preparation for validator testing
> Keiron: Clean up of codebase

- assets/css/style.css
- index.html
- I have removed this for now... so it can pass the validator.
- We can look tomorrow morning when my brain isn't fried chicken to see if we can replace it xD
@Welshy92
> Fix: Audio div/p/span tag removed for now
